### ISSUE TITLE
Trigger on off via enclosure plugin

### ISSUE THREAD

**Issue by SeekaMartin** [z4gunn/OctoPrint-GpioRgbController#1]
Hi, is there a way to trigger this with the enclosure plugin via ssh or python? I would like to be able to connect it to a physical button that does not need my printer powered on for it to work

**Comment by z4gunn** [comment]
> Hi, is there a way to trigger this with the enclosure plugin via ssh or python? I would like to be able to connect it to a physical button that does not need my printer powered on for it to work

Great feedback, let me look into adding a GPI interrupt hook for button interface.  I was also planning on adding GCODE command hooks.

**Comment by z4gunn** [comment]
> > Hi, is there a way to trigger this with the enclosure plugin via ssh or python? I would like to be able to connect it to a physical button that does not need my printer powered on for it to work
> 
> Great feedback, let me look into adding a GPI interrupt hook for button interface. I was also planning on adding GCODE command hooks.

this feature has been added to the 0.2.0 release

**Comment by z4gunn** [comment]
Closing since feature added to v0.2.0
