### ISSUE TITLE
recommended LED strips...

### ISSUE THREAD

**Issue by mikeoverbay** [z4gunn/OctoPrint-GpioRgbController#2]
I was wondering if you could put some recommended LED strips in the README.MD file.
Links to Amazon or some other store for them?
I am assuming this will work with any stander stupid LED strip and not the individually addressable types.

**Comment by z4gunn** [comment]
> I was wondering if you could put some recommended LED strips in the README.MD file.
> Links to Amazon or some other store for them?
> I am assuming this will work with any stander stupid LED strip and not the individually addressable types.

Thanks for the feedback.  I added more details in the readme regarding compatibility as well as instructions on interfacing to an external MOSFET to drive the LED strips.

**Comment by mikeoverbay** [comment]
Outstanding.. I'll close this :)
