### ISSUE TITLE
Contolling the LEDs via GCode

### ISSUE THREAD

**Issue by InfiniteP07** [z4gunn/OctoPrint-GpioRgbController#3]
It would be nice to have GCode commands control the LED-Strip automatically (like with this plugin: https://plugins.octoprint.org/plugins/ledstripcontrol/). 
Additionally it would be great to have an option (two buttons in the settings like with the "Enable input butten") to have the LEDs turn on automatically when starting a print and turning them off after the print has finished (best case is to have a timer (variable) to delay the turning off). This could also be done manually in the "GCODE Scripts" of OctoPrint in the start and end GCode, but an integrated solution would make things much easier.

Thanks for the awesome Plugin!

**Comment by z4gunn** [comment]
support for M150 GCODE command has been added in v0.3.0

**Comment by InfiniteP07** [comment]
Thanks a lot! 
Are you planning on additionally implementing the option to automaticaly have the LEDs turn on and off when starting/ finishing a print?

**Comment by z4gunn** [comment]
I think users will have a higher level of customization if they just add the appropriate M150 commands to their GCODE scripts:

For example I am using the following commands:
RGB White when print begins
RGB Green when print is finished 
RGB Red when print has error
RGB Yellow when print is paused

![image](https://user-images.githubusercontent.com/19891556/125519649-6bc74d39-aab3-4767-802d-31433003ca79.png)

**Comment by InfiniteP07** [comment]
That makes sense, thanks for the example. 
Again, thanks for the great work!
