### ISSUE TITLE
Keeps crashing my octoprint server, seems to do so by disabling wifi, but I think its just a full on hard crash

### ISSUE THREAD

**Issue by kalib98** [z4gunn/OctoPrint-GpioRgbController#5]
I installed this plugin. It worked for a while, then randomly I couldn't access octopi.local. I put my pi on a bench to see what was up, and found out that its wifi wouldn't connect while this plugin was enabled. I disabled the plugin using ethernet port and it went back to normal.

I turned the plugin back on to double check if it was the plugin, instantly crashed my octoprint server.

So something about this plugin is crashing my octoprint server.

**Comment by fieldOfView** [comment]
Are you trying to power a LED strip from the same power supply as the Pi? I think you are drawing too much power from the power supply, which causes a drop in voltage for the Pi which makes it crash.

**Comment by kalib98** [comment]
I was thinking that was the issue. But I don't have any RGB strips connected to the Pi. I'm using a Pi4 with the official power supply.

Just when I turn on the plugin, it crashes my octoprint, but mainly stops the wifi. I don't know why its doing that but I will play around with it more. The server still runs, if I plug in ethernet I can access it. Only wifi is affected.

I wonder if its the pins and I have a faulty pin thats shorting my wifi module too. I really wouldn't know.

**Comment by kalib98** [comment]
![20210716_195647](https://user-images.githubusercontent.com/10691281/126018826-7ac61374-066c-4a6f-a40e-06106c252ad2.jpg)
![20210716_195644](https://user-images.githubusercontent.com/10691281/126018827-87341d01-9ea5-4b8e-8047-1274fea75ec3.jpg)
![20210716_195622](https://user-images.githubusercontent.com/10691281/126018828-c4599a5b-73c2-4484-b651-4476c24b88d6.jpg)
![Screenshot 2021-07-16 195906](https://user-images.githubusercontent.com/10691281/126018829-f291df82-ece8-427e-91ff-b901469dd436.png)
![20210716_195703](https://user-images.githubusercontent.com/10691281/126018830-14481360-8018-4d58-bd3e-bd86eccde458.jpg)

So I decided to play around with the plugin while its connected. I can't control the LEDs using the plugin but I can using pigpio. In the screenshots I show what I mean.

Do you know what I am doing wrong? Maybe I'm missing something. I want to know if I can get it to work before i try to solve why it crashes my wifi.

**Comment by fieldOfView** [comment]
To diagnose anything, you need to post logs: https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299#a-nameheading-octoprint-hrefheading-octoprintoctoprinta-2

I don't know much about this particular plugin; I briefly looked into the way it talks to the gpio pins, and it looks like it should be possible for this plugin to use PIGPIO instead of what it does now. Perhaps @z4gunn has a nice way to configure this.

**Comment by kalib98** [comment]
[plugin_pluginmanager_console.log](https://github.com/z4gunn/OctoPrint-GpioRgbController/files/6834346/plugin_pluginmanager_console.log) [Date 13th, when it initially died]
[octoprint.log](https://github.com/z4gunn/OctoPrint-GpioRgbController/files/6834326/octoprint.log) [general log i found]
I hope this is the right file.

**Comment by fieldOfView** [comment]
The octoprint.log shows that the plugin cannot find a number of GPIO modules, which as far as I can see should have been installed when this plugin was installed. Unfortunately, the pluginmanager log seems to be from when you installed PSU control, not this plugin.

Try installing the pigpio to the oprint virtual environment:
```
source ~/oprint/bin/activate
pip install pigpio
```
The first line is important; without it, the module will be installed to the system python installation (where it probably already is), but you need it installed to the virtual environment.

**Comment by z4gunn** [comment]
Sorry I should have been a little more clear about the power supply.  You will most likely need a separate power supply to drive the LED strip.  This is how I have my system wired up.  

![image](https://user-images.githubusercontent.com/19891556/126039213-7609fd9d-2ba7-40c6-b6c0-f49d6864d944.png)

**Comment by z4gunn** [comment]
This library requires [gpiozero](https://gpiozero.readthedocs.io/en/stable/) to control the GPIO RGB states, but this dependency should be automatically installed when you install the plugin since it is in the requirements.txt.  Is it possible that you have another plugin installed that is trying to use the same pins?

**Comment by z4gunn** [comment]
> To diagnose anything, you need to post logs: https://community.octoprint.org/t/where-can-i-find-octoprints-and-octopis-log-files/299#a-nameheading-octoprint-hrefheading-octoprintoctoprinta-2
> 
> I don't know much about this particular plugin; I briefly looked into the way it talks to the gpio pins, and it looks like it should be possible for this plugin to use PIGPIO instead of what it does now. Perhaps @z4gunn has a nice way to configure this.

It looks like there is a way to configure pin factory for the [gpiozero](https://gpiozero.readthedocs.io/en/stable/api_pins.html#changing-the-pin-factory) library since it runs on top of the low level GPIO libraries.

**Comment by z4gunn** [comment]
gpiozero uses [rpigpio](https://gpiozero.readthedocs.io/en/stable/api_pins.html#module-gpiozero.pins.rpigpio) as the default pin factory.  I will add this dependency to the next release.

**Comment by z4gunn** [comment]
Please try [v0.3.2](https://github.com/z4gunn/OctoPrint-GpioRgbController/releases/tag/0.3.2)

**Comment by kalib98** [comment]
Up until not working, I did not use any other GPIO pin plugins or software. I tried installing the new version and it says "install unknown" and doesn't show up in installed plugins. So I don't know whats happening there.

![image](https://user-images.githubusercontent.com/10691281/126059302-8a8448ca-1096-4688-af3b-70379185f67b.png)

![image](https://user-images.githubusercontent.com/10691281/126059353-9393f532-7fe1-48f1-9ba6-7c6fac7f1dc8.png)

**Comment by kalib98** [comment]
I just want to say I appreciate all the help. I'm sure a bunch of this could be user error. Hopefully can get it sorted out.

**Comment by kalib98** [comment]
I just saw that version 3.3 was out. I tried it and its working! Thank you so much, this is so helpful now.

**Comment by z4gunn** [comment]
Closing issue since resolved in [v0.3.3](https://github.com/z4gunn/OctoPrint-GpioRgbController/releases/tag/0.3.3)
