### ISSUE TITLE
Color picker delay

### ISSUE THREAD

**Issue by ryanks12** [z4gunn/OctoPrint-GpioRgbController#7]
Occasionally when I use the color picker to select from the palette, there are some instances where I have already made a color selection and the color picker continues to move across the palette. 

But this only seems to happen when dragging the mouse over the color palette.

I think the problem is that there are heaps of POST requests when a user drags their mouse across the palette, which is causing some feedback delay in what is being selected.

Otherwise, good OctoPrint plugin!
Just hoping that this issue is easily fixed :)

**Comment by z4gunn** [comment]
@ryanks12  are you using v0.3.2 or above?  That version addressed a control lag issue.  I can take a look into further improvements if you are experiencing lag with latest version.

**Comment by ryanks12** [comment]
I _was_ using a version lower than 0.3.2 and have now upgrade to 0.3.3 which seems to have fixed the issue I described above.

Thank you.
